export const ru: Record<string, string> = {
  Coach: "Тренер",
  "Coach:": "Тренер:",
  "Search sessions and exercises": "Поиск тренировок и упражнений",
  "Find a session or exercise…": "Найти тренировку или упражнение…",
  "Open search": "Открыть поиск",
  "FIND. ADJUST. PROGRESS.": "НАЙТИ. ИЗМЕНИТЬ. ПРОГРЕССИРОВАТЬ.",
  "Search your training": "Поиск по тренировкам",
  "Find workouts or edit an exercise across your history and plans.":
    "Находите тренировки и изменяйте упражнение в истории и планах.",
  "Search result type": "Тип результатов поиска",
  "Search status filter": "Статус результатов поиска",
  "Search month filter": "Месяц результатов поиска",
  "Matching exercise": "Найденное упражнение",
  "All matching exercises": "Все найденные упражнения",
  "matching sessions": "найденных тренировок",
  "exercise occurrences": "выполнений и планов упражнения",
  "Type a workout or exercise name to search all your sessions.":
    "Введите название тренировки или упражнения для поиска по всей истории и планам.",
  "No matches. Try another name or change the filters.":
    "Ничего не найдено. Попробуйте другое название или измените фильтры.",
  "Previous completed": "Предыдущее выполнение",
  "Previous planned": "Предыдущий план",
  "No earlier session for this exercise": "Ранее это упражнение не встречалось",
  completed: "выполнено",
  Planner: "Планировщик",
  Library: "Библиотека",
  "Your library": "Ваша библиотека",
  "Your planner": "Ваш планировщик",
  "Planner view": "Вид планировщика",
  "Table planner": "Таблица",
  "Edit sets": "Изменить подходы",
  "Varied sets": "Разные подходы",
  "Edit individual sets": "Изменить каждый подход",
  "Remove last set": "Удалить последний подход",
  "Confirm removal": "Подтвердить удаление",
  "Open full editor": "Открыть редактор",
  "since opening planner": "с открытия таблицы",
  "Compare training weeks": "Сравнить тренировочные недели",
  "Compare week A": "Неделя A для сравнения",
  "Compare week B": "Неделя B для сравнения",
  "Volume outlook": "Прогноз объёма",
  "Edit weight and reps here. Changes preview immediately and save when you leave a field.":
    "Изменяйте вес и повторения здесь. Прогноз обновляется сразу, изменения сохраняются при выходе из поля.",
  "completed sets": "выполненных подходов",
  min: "мин",
  "Last 30 days": "Последние 30 дней",
  "More training needed": "Нужно больше тренировок",
  Exercises: "Упражнения",
  Dashboard: "Главная",
  Training: "Тренировки",
  Calendar: "Календарь",
  Analytics: "Аналитика",
  People: "Спортсмены",
  Settings: "Настройки",
  Language: "Язык",
  English: "English",
  Русский: "Русский",
  "LET'S MAKE TODAY A GOOD ONE": "СДЕЛАЕМ ЭТОТ ДЕНЬ ЛУЧШЕ",
  Hey: "Привет,",
  "Ready to move today?": "Готов к тренировке?",
  "Strong friends. Stronger days.": "Сильные друзья.\nСильнее каждый день.",
  "train together": "тренируемся вместе",
  "One rep at a time.": "Повторение за повторением.",
  "Made for showing up": "Главное — продолжать",
  "completed sets · all time": "подходов за всё время",
  "records this month": "рекордов за этот месяц",
  "Records this month": "Рекорды за месяц",
  "Completed sets": "Выполненные подходы",
  "Training volume": "Тренировочный объём",
  "Checked strength sets in the active training week. Planned sets are excluded.":
    "Объём выполненных силовых подходов за текущую тренировочную неделю. Запланированные подходы не учитываются.",
  "New estimated 1RM records this month from checked strength sets.":
    "Новые рекорды расчётного одноповторного максимума (1ПМ) за этот месяц по выполненным силовым подходам.",
  "THE BIGGER PICTURE": "ОБЩАЯ КАРТИНА",
  "Small steps. Stronger you": "Маленькие шаги. Больше силы",
  "Your progress, from every rep to every week.":
    "Ваш прогресс: от каждого повторения до каждой недели.",
  "Completed lifting volume": "Выполненный силовой объём",
  "Total weight × reps for completed strength sets, respecting the program-week filter.":
    "Сумма веса × повторений по выполненным силовым подходам с учётом фильтра A/B.",
  "All training weeks": "Все тренировочные недели",
  "Strength trend": "Динамика силы",
  "Last 30 days ·": "Последние 30 дней ·",
  "comparable exercises": "упражнений для сравнения",
  "Average percentage change in daily best estimated 1RM from each exercise's first to latest log within the last 30 days. Each exercise needs at least two different logged days and receives equal weight. Checked strength sets only; plans and zero-weight sets are excluded. This is an estimate from your logs, not a measured change in maximal strength.":
    "Среднее процентное изменение лучшего за день расчётного 1ПМ: от первой до последней записи каждого упражнения за 30 дней. Для сравнения нужны записи минимум за два разных дня. Все упражнения имеют одинаковый вес в расчёте. Учитываются только выполненные силовые подходы с положительным весом. Это оценка по журналу, а не измерение максимальной силы.",
  "Solid bars show checked strength sets. Lighter bars show remaining planned sets; the dashed line shows the combined projection. Planned sets affect only this chart. A/B week view uses assigned training groups across weekdays and month boundaries. Changes and spikes use actual volume, comparing A with the previous completed A group and B with the previous completed B group. An unfinished group can show a provisional change. Averages include only fully completed training groups, always showing both A and B averages.":
    "Насыщенные столбцы показывают выполненные подходы, светлые — оставшиеся запланированные. Пунктирная линия показывает общий прогноз. Планы влияют только на этот график. Недели A/B объединяются по назначенным группам независимо от календаря. Изменения и скачки сравнивают фактический объём A с предыдущей завершённой A и B с B. Для незавершённой группы изменение предварительное. Средние значения включают только завершённые группы A и B.",
  Session: "Тренировка",
  Week: "Неделя",
  Month: "Месяц",
  Range: "Период",
  "Training volume range": "Период объёма тренировок",
  "This month": "Этот месяц",
  "Last 3 months": "Последние 3 месяца",
  "All history": "Вся история",
  Bars: "Столбцы",
  Line: "Линия",
  Projection: "Прогноз",
  Completed: "Выполнено",
  Planned: "Запланировано",
  "Show breakdown": "Показать подробности",
  Period: "Период",
  Change: "Изменение",
  Workload: "Нагрузка",
  "No previous data": "Нет данных для сравнения",
  "· In progress": "· В процессе",
  "↑ Workload spike": "↑ Скачок нагрузки",
  "Week A avg": "Среднее A",
  "Week B avg": "Среднее B",
  "compared with Week B": "по сравнению с B",
  "Your progress starts with a rep": "Прогресс начинается с повторения",
  "Complete a lifting set to populate volume history.":
    "Выполните силовой подход, чтобы появился график объёма.",
  "Warm-up checklist": "Разминка и заминка",
  "Warm-up": "Разминка",
  "Cool-down": "Заминка",
  "Warm-ups": "Разминки",
  "Cool-downs": "Заминки",
  "Each column is one session: warm-up on top and cool-down below. Tap a box for details. Green means done, amber means partial, gray means skipped, pending or not planned. Shows warm-ups and cool-downs for sessions with completed sets or activities. Future plans that have not started are excluded.":
    "Каждый столбец — одна тренировка: сверху разминка, снизу заминка. Нажмите на квадрат, чтобы увидеть подробности. Зелёный — выполнено, жёлтый — частично, серый — пропущено, ожидается или не запланировано. Показываются только начатые тренировки. Будущие планы не учитываются.",
  "Done means every activity in that routine was marked complete. Partial means only some were completed. Skipped means it was not marked complete in a finished or past training session. Pending means today’s session is still in progress. Not planned means the session contains no activity of that kind.":
    "Выполнено: отмечены все упражнения блока. Частично: выполнена часть. Пропущено: блок не отмечен в завершённой или прошедшей тренировке. Ожидается: сегодняшняя тренировка ещё идёт. Не запланировано: такого блока нет в тренировке.",
  "Recovery completion stays separate from lifting volume, estimated 1RM and records.":
    "Разминка и заминка не влияют на силовой объём, расчётный 1ПМ и рекорды.",
  Done: "Готово",
  Partial: "Частично",
  Skipped: "Пропущено",
  Pending: "Ожидается",
  "Not planned": "Не запланировано",
  "Not done / not planned": "Не выполнено / не запланировано",
  "activities completed": "упражнений выполнено",
  "Your warm-up checklist starts here": "Здесь будет история разминок",
  "Complete a set or recovery activity to add a training session.":
    "Выполните подход, разминку или заминку, чтобы добавить тренировку.",
  "Warm-up and cool-down session history": "История разминок и заминок",
  "Session recovery checks": "Разминка и заминка по тренировкам",
  "Exercise progress": "Прогресс упражнений",
  "Lines connect recorded training days. An exercise with one recorded day has one point; missing days are not treated as zero.":
    "Линии соединяют дни с записями. Если запись одна, показывается одна точка. Дни без записей не считаются нулевыми.",
  "Epley estimate: weight × (1 + reps ÷ 30). Bodyweight movements need a entered lifting weight to produce a weight-based estimate.":
    "Формула Эпли: вес × (1 + повторения ÷ 30). Для упражнений с собственным весом нужно указать поднимаемый вес, чтобы получить оценку.",
  "0% is each exercise’s first completed":
    "0% — первая выполненная запись каждого упражнения:",
  "top weight": "максимальный вес",
  "estimated 1RM": "расчётный 1ПМ",
  "in the selected month": "за выбранный месяц",
  "across all recorded history": "за всю историю",
  "Estimated 1RM": "Расчётный 1ПМ",
  "Top weight": "Максимальный вес",
  Display: "Отображение",
  "Weight (kg)": "Вес (кг)",
  "Growth (%)": "Рост (%)",
  "Select one or more exercises to compare completed performance.":
    "Выберите упражнения, чтобы сравнить результаты выполненных подходов.",
  "No completed history for this selection":
    "Нет выполненных подходов для выбранных упражнений",
  "Finish a set with weight and reps to get started.":
    "Выполните подход с весом и повторениями, чтобы начать.",
  "Personal records": "Личные рекорды",
  "The first five exercises are ranked by completed-set frequency. Records respect the week filter.":
    "Первые пять упражнений показаны по частоте выполненных подходов. Рекорды учитывают фильтр недели.",
  "More exercises": "Больше упражнений",
  "Show less": "Свернуть",
  Exercise: "Упражнение",
  "Best e1RM": "Лучший расчётный 1ПМ",
  Heaviest: "Наибольший вес",
  "Best set": "Лучший подход",
  Date: "Дата",
  "Your first record is waiting": "Первый рекорд впереди",
  "Complete your first session.": "Завершите первую тренировку.",
  Bodyweight: "Вес тела",
  "Average of measurements in the preceding seven calendar days, including the entry date. Bodyweight is independent of the program-week filter.":
    "Среднее измерений за предыдущие семь календарных дней, включая дату записи. Вес тела не зависит от фильтра недели A/B.",
  "Log bodyweight": "Записать вес",
  "Latest ·": "Последний ·",
  "· 7-day average": "· Среднее за 7 дней",
  "7-day average": "Среднее за 7 дней",
  "7-day moving average": "Среднее за 7 дней",
  "Bodyweight entries": "Записи веса тела",
  "Bodyweight (kg)": "Вес тела (кг)",
  "Save bodyweight": "Сохранить вес",
  "An existing entry on this date will be updated.":
    "Существующая запись за эту дату будет обновлена.",
  "Log your bodyweight to see its history and 7-day trend.":
    "Запишите вес тела, чтобы увидеть историю и среднее за 7 дней.",
  "Room for your next goal": "Место для следующей цели",
  "All weeks": "Все недели",
  "Week A": "Неделя A",
  "Week B": "Неделя B",
  "Week A only": "Только неделя A",
  "Week B only": "Только неделя B",
  "Today's workout": "Сегодняшняя тренировка",
  Plan: "Запланировать",
  "Open editor": "Открыть редактор",
  "Complete session": "Завершить тренировку",
  "Coming up": "Предстоящие",
  "Recently completed": "Недавно завершённые",
  "View all": "Смотреть все",
  "Nothing planned yet": "Пока ничего не запланировано",
  "Plan your next training day.": "Запланируйте следующую тренировку.",
  "Your history starts here": "Здесь будет ваша история",
  "A fresh page for today": "Новый день — новые возможности",
  "Plan a session, or enjoy your recovery day.":
    "Запланируйте тренировку или наслаждайтесь днём отдыха.",
  "Plan today's session": "Запланировать на сегодня",
  "Keep showing up!": "Продолжайте тренироваться!",
  "Every rep is a little vote for you.": "Каждое повторение — вклад в себя.",
  "SHOW UP. LIFT. REPEAT.": "ПРИХОДИ. ТРЕНИРУЙСЯ. ПОВТОРЯЙ.",
  "Your training": "Ваши тренировки",
  "A place for every session and every small win.":
    "Место для каждой тренировки и маленькой победы.",
  "Create session": "Создать тренировку",
  Sessions: "Тренировки",
  Templates: "Шаблоны",
  "Exercise library": "Библиотека упражнений",
  "All sessions": "Все тренировки",
  "Past months": "Прошлые месяцы",
  "All past months": "Все прошлые месяцы",
  "All months": "Все месяцы",
  "Your next chapter starts here": "Новая глава начинается здесь",
  "No sessions in this view": "Нет тренировок в этом разделе",
  "No matching sessions": "Тренировки не найдены",
  "Try another session name or switch the month or history period.":
    "Попробуйте другое название, месяц или период истории.",
  "Choose another month, All history, or a different status filter. You can also plan a new session.":
    "Выберите другой месяц, всю историю или другой статус. Можно также запланировать новую тренировку.",
  "Your routine, ready to repeat": "Ваш план готов к повторению",
  "Create a template or save one from any session.":
    "Создайте шаблон или сохраните его из любой тренировки.",
  "Create template": "Создать шаблон",
  "Reusable training plan": "План для повторения",
  "exercises ·": "упражнений ·",
  "Start session": "Начать тренировку",
  Edit: "Изменить",
  "Shared with your coach and their athletes. Everyone can add exercises; your coach manages videos and removes exercises.":
    "Общая библиотека тренера и его спортсменов. Все могут добавлять упражнения; тренер управляет видео и удалением.",
  "Shared exercises will be available after your coach enables the library update. Your current library still works.":
    "Общая библиотека появится после обновления у тренера. Текущая библиотека продолжает работать.",
  "Find an exercise…": "Найти упражнение…",
  "Custom exercise name": "Название своего упражнения",
  "Add your own exercise…": "Добавить своё упражнение…",
  Add: "Добавить",
  Shared: "Общее",
  "Built-in": "Встроенное",
  Watch: "Смотреть",
  "Add video": "Добавить видео",
  "Edit video": "Изменить видео",
  "Removing a custom exercise preserves its logged history.":
    "Удаление упражнения сохраняет историю выполненных подходов.",
  "Exercise added to the library.": "Упражнение добавлено в библиотеку.",
  "Exercise removed. Logged history is preserved.":
    "Упражнение удалено. История сохранена.",
  "Adding exercise…": "Добавляем упражнение…",
  "PLAN. TRAIN. PROGRESS.": "ПЛАНИРУЙ. ТРЕНИРУЙСЯ. РАЗВИВАЙСЯ.",
  "Your training calendar": "Календарь тренировок",
  "Make a little space for getting stronger.":
    "Найдите время, чтобы стать сильнее.",
  "Add session": "Добавить тренировку",
  Today: "Сегодня",
  Mon: "Пн",
  Tue: "Вт",
  Wed: "Ср",
  Thu: "Чт",
  Fri: "Пт",
  Sat: "Сб",
  Sun: "Вс",
  "No session planned": "Нет запланированной тренировки",
  "✓ Done": "✓ Выполнено",
  "Tap a date to plan, or a session to open it. Drag a session to reschedule on desktop. Use “Move to date” in the editor on mobile.":
    "Нажмите на дату для планирования или на тренировку для просмотра. На компьютере дату можно изменить перетаскиванием, на телефоне — через «Перенести на дату» в редакторе.",
  "Training weeks": "Тренировочные недели",
  "Calendar weeks": "Календарные недели",
  "Training-week projection": "Прогноз тренировочных недель",
  "Month projection": "Прогноз месяца",
  "Calendar volume outlook": "Прогноз объёма в календаре",
  "Weekly lifting volume, calculated as weight × reps. Completed sessions use only checked sets. Planned sessions use all prescribed sets, including checked sets until the session is marked done. These are estimates, not additional completed volume.":
    "Недельный силовой объём: вес × повторения. В завершённых тренировках учитываются выполненные подходы. В запланированных — все заданные подходы до завершения тренировки. Это прогноз, а не дополнительный выполненный объём.",
  "Bars stack lighter planned volume above solid completed volume. Week A and B use the session’s assigned program week. Lines show completed volume and the combined projection.":
    "Светлый запланированный объём расположен над насыщенным выполненным. A/B определяются назначенной неделей программы. Линии показывают выполненный объём и общий прогноз.",
  "Training weeks combine assigned sessions, regardless of weekdays. Unassigned history is suggested in consecutive groups of up to three sessions with the same A/B tag. Whole groups with a session in this month are shown, including sessions outside the month. Change assignments in the session editor.":
    "Тренировочные недели объединяют назначенные тренировки независимо от дней недели. Старая история без групп объединяется по три последовательные тренировки с одинаковой меткой A/B. Показывается вся группа, если хотя бы одна тренировка входит в месяц. Назначения меняются в редакторе.",
  "Warm-ups and cool-downs do not add lifting volume.":
    "Разминки и заминки не добавляют силовой объём.",
  "Some training weeks cross month boundaries. Their totals include the whole group; date ranges show which sessions are included.":
    "Некоторые тренировочные недели пересекают границу месяца. Их объём включает всю группу.",
  "No lifting volume yet for this month. Add weight and reps to planned sessions to see your projection.":
    "В этом месяце пока нет силового объёма. Добавьте вес и повторения в планы, чтобы увидеть прогноз.",
  Dates: "Даты",
  "Weekly lifting volume for": "Недельный объём за",
  "STRONGER TOGETHER": "ВМЕСТЕ СИЛЬНЕЕ",
  "Your training crew": "Ваша команда",
  "Plan their sessions. Celebrate their progress.":
    "Планируйте тренировки и радуйтесь прогрессу.",
  "Invite athlete": "Пригласить спортсмена",
  Active: "Активен",
  Inactive: "Неактивен",
  "Next:": "Далее:",
  "Last:": "Последняя:",
  "No completed session": "Нет завершённых тренировок",
  "Loading training summary…": "Загружаем сводку тренировок…",
  Manage: "Управление",
  "Deactivate access": "Отключить доступ",
  "Reactivate access": "Включить доступ",
  "Build your crew": "Соберите команду",
  "Invite your first athlete to plan training together.":
    "Пригласите первого спортсмена для совместного планирования.",
  "YOUR DATA, YOUR JOURNEY": "ВАШИ ДАННЫЕ, ВАШ ПУТЬ",
  "Make it yours": "Настройте под себя",
  "Training preferences and backups.":
    "Настройки тренировок и резервные копии.",
  "Choose an athlete at the top to personalize their app name, dashboard and menu.":
    "Выберите спортсмена сверху, чтобы настроить название приложения, сообщение на главной и меню.",
  "Program & workload": "Программа и нагрузка",
  "Display name": "Отображаемое имя",
  "Use A/B split": "Использовать A/B",
  "Alternate between Week A and Week B.": "Чередование недель A и B.",
  "This preference needs an account settings update before it can be changed.":
    "Для изменения этой настройки требуется обновление аккаунта.",
  "Plan freely, with all sessions in one program. Your existing workouts are kept.":
    "Планируйте свободно в одной программе. Существующие тренировки сохранятся.",
  "Week A/B anchor date": "Начальная дата A/B",
  "Anchor program week": "Начальная неделя программы",
  "Your dashboard alternates A/B from this date's Monday. Existing sessions retain their assigned week.":
    "Главная чередует A/B с понедельника этой даты. Существующие тренировки сохраняют назначенные недели.",
  "Workload spike threshold (%)": "Порог скачка нагрузки (%)",
  "Flag weekly volume increases above this threshold. Default: 30%.":
    "Отмечать рост недельного объёма выше этого порога. По умолчанию: 30%.",
  Account: "Аккаунт",
  Athlete: "Спортсмен",
  "Sign out": "Выйти",
  "Leave demo": "Выйти из демо",
  "Data & backups": "Данные и копии",
  "Export all data": "Экспортировать все данные",
  "Sessions, templates, exercises, bodyweight & settings":
    "Тренировки, шаблоны, упражнения, вес тела и настройки",
  "Import JSON backup": "Импортировать JSON-копию",
  "Restore everything for": "Восстановить все данные для",
  "Load demo data": "Загрузить демоданные",
  "Eight weeks of A/B workouts & progress":
    "Восемь недель A/B тренировок и прогресса",
  "Clear all training data": "Очистить все тренировки",
  "Only the selected athlete's data": "Только данные выбранного спортсмена",
  "You are using a local demo. These are simulated profiles; no invitations are sent.":
    "Вы используете локальное демо. Профили тестовые, приглашения не отправляются.",
  "Connect accounts →": "Подключить аккаунты →",
  "Demo mode · profiles and workouts stay in this browser":
    "Деморежим · профили и тренировки хранятся в этом браузере",
  "Use real account →": "Открыть настоящий аккаунт →",
  "Local demo": "Локальное демо",
  "Switch athlete": "Выбрать спортсмена",
  "Search sessions": "Поиск тренировок",
  "Find a session…": "Найти тренировку…",
  "All saved": "Всё сохранено",
  "Unsaved changes": "Несохранённые изменения",
  "Saving…": "Сохраняем…",
  "You are editing as their coach.": "Вы редактируете как тренер.",
  Viewing: "Просмотр",
  "Open navigation": "Открыть меню",
  "Open setup instructions": "Инструкция по настройке",
  "See the repository README to connect Supabase for real accounts.":
    "Для подключения настоящих аккаунтов Supabase смотрите README репозитория.",
  Export: "Экспорт",
  Reload: "Перезагрузить",
  "Reload saved data and discard unsaved edits? Export first to keep them.":
    "Перезагрузить сохранённые данные и отменить несохранённые изменения? Сначала экспортируйте их для сохранения.",
  More: "Ещё",
  "Your workout": "Ваша тренировка",
  "Edit template": "Изменить шаблон",
  "Choose emoji": "Выбрать эмодзи",
  "Choose your energy": "Выберите настроение",
  "Or enter an icon": "Или введите значок",
  "Session name": "Название тренировки",
  "New template": "Новый шаблон",
  "Completed · nice work!": "Выполнено · отличная работа!",
  "Planned · ready when you are": "Запланировано · можно начинать",
  "Exercises & sets": "Упражнения и подходы",
  "Drag the grip to rearrange exercises, or use the arrows.":
    "Перетаскивайте упражнения за ручку или используйте стрелки.",
  "Let's build your session": "Соберём вашу тренировку",
  "Add strength work, a warm-up or a cool-down.":
    "Добавьте силовые упражнения, разминку или заминку.",
  "Add exercise": "Добавить упражнение",
  "Template details": "Параметры шаблона",
  "Session details": "Параметры тренировки",
  "Move to date": "Перенести на дату",
  "Program week": "Неделя программы",
  "Training week": "Тренировочная неделя",
  "Start a new Week": "Начать новую неделю",
  "Group sessions regardless of dates. Three sessions is the default suggestion; add more or fewer as needed.":
    "Объединяйте тренировки независимо от дат. По умолчанию — три тренировки, но можно больше или меньше.",
  "Your coach needs to run database upgrade 007 to save custom training-week assignments. The chart uses suggested groups meanwhile.":
    "Тренеру нужно выполнить обновление базы 007 для сохранения групп тренировочных недель. Пока график использует предложенные группы.",
  Status: "Статус",
  "How did it feel?": "Как прошла тренировка?",
  "Not rated": "Без оценки",
  "😌 Easy": "😌 Легко",
  "🙂 Solid": "🙂 Хорошо",
  "😤 Hard": "😤 Тяжело",
  "🔥 Brutal": "🔥 Очень тяжело",
  Notes: "Заметки",
  "Form cues, goals, how you felt…": "Техника, цели, ощущения…",
  Volume: "Объём",
  Save: "Сохранить",
  "Save session": "Сохранить тренировку",
  "Save template": "Сохранить шаблон",
  "Save as template": "Сохранить как шаблон",
  "✓ Template saved": "✓ Шаблон сохранён",
  "Delete session": "Удалить тренировку",
  "Delete template": "Удалить шаблон",
  Delete: "Удалить",
  "Pick your exercises": "Выберите упражнения",
  "Search or name exercise": "Найдите или назовите упражнение",
  Strength: "Силовое",
  "Name this activity…": "Назовите упражнение…",
  "First time here. Make it count!": "Первая запись. Хорошего начала!",
  "Exercise name": "Название упражнения",
  Close: "Закрыть",
  Set: "Подход",
  Weight: "Вес",
  Reps: "Повт.",
  "Add set": "Добавить подход",
  "Duration (minutes)": "Длительность (минуты)",
  "Exercise notes": "Заметки к упражнению",
  "Form cues or instructions…": "Подсказки по технике или инструкции…",
  "How it felt, technique, what to adjust next time…":
    "Ощущения, техника, что изменить в следующий раз…",
  "Save exercise": "Сохранить упражнение",
  "Read note": "Читать заметку",
  "Tap to edit": "Нажмите для изменения",
  "· Tap to edit": "· Нажмите для изменения",
  "Last ·": "Прошлый раз ·",
  kg: "кг",
  "kg ×": "кг ×",
  "kg on": "кг ·",
  sets: "подх.",
  of: "из",
  Complete: "Завершить",
  Reopen: "Открыть снова",
  Hide: "Скрыть",
  Read: "Читать",
  "not completed": "не выполнено",
  "Workout complete": "Тренировка завершена",
  "Total volume": "Общий объём",
  Saved: "Сохранено",
  "Not saved · check the error above": "Не сохранено · проверьте ошибку выше",
  "Edit workout": "Изменить тренировку",
  "Nice work! Workout complete.": "Отличная работа! Тренировка завершена.",
  "Dismiss workout confirmation": "Скрыть подтверждение тренировки",
  "Watch technique": "Смотреть технику",
  "Hide technique": "Скрыть технику",
  "Open in Google Drive": "Открыть в Google Drive",
  "If playback is unavailable, open the video in Drive. Your coach may need to update sharing access.":
    "Если видео не воспроизводится, откройте его в Drive. Возможно, тренеру нужно настроить доступ.",
  "Technique video (Google Drive)": "Видео техники (Google Drive)",
  "Upload your demonstration to Drive and give your athlete access. “Anyone with the link → Viewer” lets anyone holding the link view it. This link is reused for this exercise across their workouts.":
    "Загрузите видео в Drive и предоставьте спортсмену доступ. Режим «Все, у кого есть ссылка → Читатель» позволяет смотреть видео любому с этой ссылкой. Видео доступно во всех тренировках с этим упражнением.",
  "Paste your Google Drive video link…":
    "Вставьте ссылку на видео Google Drive…",
  "Save video": "Сохранить видео",
  "Remove video": "Удалить видео",
  "Technique video saved.": "Видео техники сохранено.",
  "Technique video removed.": "Видео техники удалено.",
  "Could not save the video.": "Не удалось сохранить видео.",
  "Technique videos will be available after the account update.":
    "Видео техники появятся после обновления аккаунта.",
  "App name": "Название приложения",
  "Dashboard message": "Сообщение на главной",
  "Menu message": "Сообщение в меню",
  "Save personalization": "Сохранить оформление",
  "Personalization saved.": "Настройки оформления сохранены.",
  "Could not save personalization.": "Не удалось сохранить оформление.",
  "Personal messages will be available after the account update.":
    "Личные сообщения появятся после обновления аккаунта.",
  "Personal app names will be available after the account update.":
    "Личные названия появятся после обновления аккаунта.",
  "Plan a session": "Запланировать тренировку",
  "Start a blank session": "Начать пустую тренировку",
  "Or use a template": "Или используйте шаблон",
  "Duplicate session": "Дублировать тренировку",
  "Copy the exercises, weights and reps to a new planned session. All sets will be unchecked.":
    "Упражнения, веса и повторения будут скопированы в новую запланированную тренировку. Все отметки выполнения будут сняты.",
  "New session date": "Дата новой тренировки",
  "Duplicate & edit": "Дублировать и изменить",
  Cancel: "Отмена",
  "Invite an athlete": "Пригласить спортсмена",
  Name: "Имя",
  Email: "Эл. почта",
  "They'll receive a secure link to set their password.":
    "Спортсмен получит защищённую ссылку для установки пароля.",
  "Send invitation": "Отправить приглашение",
  "Sending…": "Отправляем…",
  "Invitations need a connected Supabase project and your Coach account. Demo profiles are browser-only simulations.":
    "Для приглашений нужен подключённый Supabase и аккаунт тренера. Демопрофили существуют только в браузере.",
  "Clear training data?": "Очистить данные тренировок?",
  "Load demo data?": "Загрузить демоданные?",
  "Restore this backup?": "Восстановить копию?",
  "This replaces all training data for":
    "Это заменит все тренировочные данные для",
  "Export a backup first if you want to keep the current data.":
    "Сначала экспортируйте копию, чтобы сохранить текущие данные.",
  "Replace data": "Заменить данные",
  "Export first": "Сначала экспортировать",
  "Delete this": "Удалить",
  "Yes, delete": "Да, удалить",
  ". Other athletes are unaffected.":
    ". Данные других спортсменов не изменятся.",
  "'s training": ": тренировки",
  "It removes the entry for the coach’s group. Your coach can re-add the same name to restore it.":
    "Упражнение удаляется из группы тренера. Тренер может восстановить его, добавив то же название.",
  "Welcome back, strong friend.": "С возвращением!",
  "Your next session is waiting.": "Ваша следующая тренировка ждёт.",
  Password: "Пароль",
  "Sign in": "Войти",
  "Signing in…": "Входим…",
  "Forgot password?": "Забыли пароль?",
  "Try the demo": "Попробовать демо",
  "Real accounts are invited by your coach.":
    "Настоящие аккаунты создаются по приглашению тренера.",
  "Enter your email first.": "Сначала введите эл. почту.",
  "If this account exists, a password reset link has been sent.":
    "Если аккаунт существует, письмо для сброса пароля отправлено.",
  "Set your password": "Установите пароль",
  "Ready for your next session.": "Готовы к следующей тренировке.",
  "New password": "Новый пароль",
  "Save password": "Сохранить пароль",
  "LiftLog hit a snag": "В LiftLog возникла ошибка",
  "Your saved data is still available. Reload to try again.":
    "Сохранённые данные доступны. Перезагрузите страницу и попробуйте снова.",
  "Opening LiftLog…": "Открываем LiftLog…",
  "Loading your training…": "Загружаем тренировки…",
  "Resolve the loading error above to continue.":
    "Исправьте ошибку загрузки выше, чтобы продолжить.",
  "This account is inactive or has not been set up. Contact your coach.":
    "Аккаунт неактивен или не настроен. Свяжитесь с тренером.",
  "Coach access required": "Нужен доступ тренера",
  "Only your coach can remove shared exercises.":
    "Только тренер может удалять общие упражнения.",
  "Browser storage is full or unavailable. Export your data before leaving.":
    "Хранилище браузера заполнено или недоступно. Экспортируйте данные перед выходом.",
  "Finish saving or export and reload your unsaved changes before switching athletes.":
    "Дождитесь сохранения или экспортируйте изменения и перезагрузите страницу перед сменой спортсмена.",
  "Finish syncing training changes before saving a video.":
    "Дождитесь синхронизации тренировок перед сохранением видео.",
  "Save or export unsaved data before signing out.":
    "Сохраните или экспортируйте изменения перед выходом.",
  "Export unsaved data before signing out.":
    "Экспортируйте изменения перед выходом.",
  "Backup is too large (10 MB maximum).":
    "Копия слишком большая (максимум 10 МБ).",
  "No exercises planned yet": "Упражнения пока не запланированы",
  "Open the session to add your exercises.":
    "Откройте тренировку, чтобы добавить упражнения.",
  "Create a session or load demo data from Settings.":
    "Создайте тренировку или загрузите демоданные в настройках.",
  All: "Все",
  "All time": "Всё время",
  "No sets planned": "Подходы не запланированы",
  "Language is saved on this device until the account language update is applied.":
    "До обновления настроек языка в базе выбор сохраняется только на этом устройстве.",
  "Language is synced with this athlete's account.":
    "Язык сохраняется в аккаунте спортсмена.",
  "completed:": "выполнено:",
  "planned:": "запланировано:",
  "projection:": "прогноз:",
  "kg; projection:": "кг; прогноз:",
  "Bench Press": "Жим лёжа",
  "Incline Dumbbell Press": "Жим гантелей на наклонной скамье",
  "Overhead Press": "Жим над головой",
  "Triceps Pushdown": "Разгибание рук на блоке",
  "Barbell Row": "Тяга штанги в наклоне",
  "Lat Pulldown": "Тяга верхнего блока",
  "Biceps Curl": "Сгибание рук на бицепс",
  "Barbell Back Squat": "Приседания со штангой",
  "Romanian Deadlift": "Румынская тяга",
  "Leg Curl": "Сгибание ног",
  "Calf Raise": "Подъёмы на носки",
  Deadlift: "Становая тяга",
  "Pull-Up": "Подтягивания",
  "Leg Press": "Жим ногами",
  "Seated Cable Row": "Тяга горизонтального блока",
  "Lateral Raise": "Разведение гантелей в стороны",
  "Light cardio & mobility": "Лёгкое кардио и разминка",
  "Stretch & breathe": "Растяжка и дыхание",
  set: "подход",
  You: "Вы",
  inactive: "неактивен",
  "This calendar week": "Текущая календарная неделя",
  "This training week": "Текущая тренировочная неделя",
  "Analytics week filter": "Фильтр недель аналитики",
  "Exercise progress period": "Период прогресса упражнения",
  "Exercise progress metric": "Показатель прогресса упражнения",
  "Exercise progress scale": "Шкала прогресса упражнения",
  "Training history period": "Период истории тренировок",
  "Training status filter": "Фильтр статуса тренировок",
  "Calendar view": "Вид календаря",
  "Chart view": "Вид графика",
  "session volume \u00b7 kg": "Объём по тренировкам · кг",
  "week volume \u00b7 kg": "Объём по неделям · кг",
  "month volume \u00b7 kg": "Объём по месяцам · кг",
  "A little more context": "Немного подробнее",
  "Analytics volume chart view": "Вид графика объёма в аналитике",
  "Calendar volume chart view": "Вид графика объёма в календаре",
  "Session status filter": "Фильтр статуса тренировок",
  "Training month filter": "Месяц тренировок",
  "Volume week grouping": "Группировка недель",
  "Open training": "Открыть тренировки",
  session: "тренировка",
  sessions: "тренировок",
  template: "шаблон",
  "Language is saved separately for each demo athlete on this device.":
    "Язык сохраняется отдельно для каждого демопрофиля на этом устройстве.",
  planned: "запланировано",
  done: "завершено",
  coach: "тренер",
  athlete: "спортсмен",
  selected: "выбрано",
  "Search exercises": "Поиск упражнений",
  "Clear selection": "Снять выбор",
  "No matching exercises": "Упражнения не найдены",
  Inbox: "Входящие",
  unread: "непрочитанных",
  Unread: "Непрочитанные",
  Reviewed: "Просмотренные",
  "COACH CHECK-IN": "ОБЗОР ТРЕНЕРА",
  "Workout inbox": "Тренировки на проверку",
  "New completed workouts and later changes appear here.":
    "Здесь появляются новые завершённые тренировки и последующие изменения.",
  Refresh: "Обновить",
  "Coach inbox needs an account update before notifications can appear.":
    "Для уведомлений нужно обновить настройки аккаунта.",
  "Inbox tabs": "Разделы входящих",
  "Inbox athlete filter": "Фильтр по спортсмену",
  "All athletes": "Все спортсмены",
  "The latest three reviewed workouts per athlete are shown here. Older review status is kept.":
    "Здесь показаны последние три просмотренные тренировки каждого спортсмена. Статус более ранних проверок сохранён.",
  "Notes left": "Есть заметки",
  Updated: "Обновлено",
  New: "Новое",
  "Loading inbox…": "Загружаем входящие…",
  "All caught up": "Всё просмотрено",
  "No reviewed workouts yet": "Просмотренных тренировок пока нет",
  "New completions will appear here. Existing workout history stays in Training.":
    "Здесь появятся новые завершённые тренировки. Прежняя история остаётся в разделе «Тренировки».",
  "Open an unread workout to review its exercises and notes.":
    "Откройте непрочитанную тренировку, чтобы посмотреть упражнения и заметки.",
  "Saving review…": "Сохраняем просмотр…",
  "Session notes": "Заметки к тренировке",
  "Not done": "Не выполнено",
  "Mark unread": "Отметить непрочитанной",
  "This workout is no longer in the inbox":
    "Этой тренировки больше нет во входящих",
  "Workout changed. Refresh the inbox before reviewing.":
    "Тренировка изменилась. Обновите входящие перед просмотром.",
  "Strength · 30 days": "Сила · 30 дней",
  "Volume · 30 days": "Объём · 30 дней",
  "Checked strength sets in the last 30 days, including today. Planned sets and future logs are excluded.":
    "Выполненные силовые подходы за последние 30 дней, включая сегодня. Планы и будущие записи не учитываются.",
  "Total weight × reps for checked strength sets in the last 30 days, respecting the program-week filter. Planned sets and future logs are excluded.":
    "Сумма веса × повторений для выполненных силовых подходов за последние 30 дней с учётом фильтра недель. Планы и будущие записи не учитываются.",
  "Combined strength trend": "Общий тренд силы",
  "Strength trend range": "Период тренда силы",
  "Each exercise starts at 0% from its first daily best estimated 1RM in the selected period. The line averages the changes equally across comparable exercises. An exercise needs at least two logged days in that period. Between logs, its last recorded performance is carried forward.":
    "Для каждого упражнения 0% — это первая лучшая дневная оценка 1ПМ за выбранный период. Линия показывает среднее изменение с равным вкладом сопоставимых упражнений. Нужно минимум два дня записей за этот период. Между записями используется последний результат.",
  "Exercises join the line on their first recorded day, so the number contributing can grow over time. Planned and zero-weight sets are excluded. The 30-day endpoint matches the strength summary.":
    "Упражнения входят в расчёт с первого дня записи, поэтому их количество может расти. Планы и подходы с нулевым весом исключены. Итог за 30 дней совпадает с карточкой силы.",
  "Log an exercise on at least two different days to see its strength trend.":
    "Запишите упражнение хотя бы в два разных дня, чтобы увидеть тренд силы.",
  "Each column is one session: warm-up on top and cool-down below. Tap a box for details. Green means done, amber means partial, gray means skipped, pending or not planned. Shows the last 12 sessions with completed sets or activities. Future plans that have not started are excluded.":
    "Каждый столбец — одна тренировка: сверху разминка, снизу заминка. Нажмите на ячейку для подробностей. Зелёный — выполнено, жёлтый — частично, серый — пропущено, ожидается или не запланировано. Показаны последние 12 тренировок с выполненными подходами или активностями. Будущие планы без выполненных активностей исключены.",
  "View strength breakdown": "Посмотреть динамику силы",
  "View volume breakdown": "Посмотреть подробности объёма",
  "View records this month": "Посмотреть рекорды за этот месяц",
  "New estimated 1RM records this month":
    "Новые рекорды расчётного 1ПМ за этот месяц",
  "Each exercise contributes equally. First and latest daily best estimated 1RM are shown below.":
    "Упражнения имеют равный вклад. Ниже показаны первая и последняя лучшие дневные оценки 1ПМ.",
  "Only checked strength sets count. Tap a workout to open it.":
    "Учитываются только выполненные силовые подходы. Нажмите на тренировку, чтобы открыть её.",
  "Open workout": "Открыть тренировку",
  "No completed sets yet": "Выполненных подходов пока нет",
  "Each entry is a new estimated 1RM record, including your first recorded result. Tap to open its workout.":
    "Каждая запись — новый рекорд расчётного 1ПМ, включая первый записанный результат. Нажмите, чтобы открыть тренировку.",
  "Open record workout": "Открыть тренировку с рекордом",
  "No new records this month": "В этом месяце новых рекордов пока нет",
  "Your next personal record will appear here.":
    "Ваш следующий личный рекорд появится здесь.",
  pp: "п.п.",
  "New exercise joined at its 0% baseline.":
    "Новое упражнение вошло в расчёт с базовым значением 0%.",
  "Daily best estimated 1RM updated.": "Лучшая дневная оценка 1ПМ обновилась.",
  "Previous performance carried forward; no effect on this change.":
    "Использован предыдущий результат; на это изменение он не повлиял.",
  "Previous log": "Предыдущая запись",
  "Latest log": "Последняя запись",
  "Growth from baseline": "Изменение от базового значения",
  "Starting point": "Начальная точка",
  "Change from previous point": "Изменение от предыдущей точки",
  "Previous point": "Предыдущая точка",
  "Contributions below add up to the movement of the combined line. Percentage points describe the change in that average.":
    "Вклад упражнений ниже в сумме даёт изменение общей линии. Процентные пункты показывают изменение этого среднего.",
  "New exercises enter at 0%. Adding them can pull a positive average down, or a negative average up, even without a lower logged performance.":
    "Новые упражнения входят с 0%. Их добавление может снизить положительное среднее или повысить отрицательное даже без снижения записанных результатов.",
  "This is the first plotted date. Exercises begin at their own 0% baselines; there is no previous point to compare.":
    "Это первая дата на графике. Упражнения начинают со своих базовых значений 0%; предыдущей точки для сравнения нет.",
  "No exercise changed its contribution at this point.":
    "В этой точке вклад ни одного упражнения не изменился.",
  "Show full breakdown": "Показать полный расчёт",
  "This explains recorded performance, not measured strength loss. Lighter weights or fewer reps may reflect a deliberately easier workout.":
    "Это объяснение записанных результатов, а не измеренная потеря силы. Меньший вес или меньше повторений могут отражать намеренно лёгкую тренировку.",
  "View strength changes": "Посмотреть причины изменения силы",
  "Tap a point or choose a date": "Нажмите на точку или выберите дату",
  "Strength trend date": "Дата на графике силы",
  "Choose a date": "Выберите дату",
  "Change exercise": "Заменить упражнение",
  "Choose or create exercise": "Выберите или создайте упражнение",
  "Choose from exercise library": "Выбрать из библиотеки упражнений",
  "Use exercise": "Использовать упражнение",
  "Create and use exercise": "Создать и использовать",
  "Changes this exercise in this workout only. Sets and notes are kept; search and analytics use the new exercise.":
    "Заменяется только упражнение в этой тренировке. Подходы и заметки сохраняются; поиск и аналитика используют новое упражнение.",
  "Volume (kg)": "Объём (кг)",
  "Inspect a progress point": "Посмотреть точку прогресса",
  "Choose a point": "Выберите точку",
  "Volume adds weight × reps for all completed sets of this exercise on this day, across workouts. Unchecked sets are excluded.":
    "Объём — сумма веса × повторений всех выполненных подходов этого упражнения за день, во всех тренировках. Невыполненные подходы не учитываются.",
  "This point uses the best completed set on this day. Highlighted sets determine the plotted value; unchecked sets are excluded.":
    "Точка показывает лучший выполненный подход за день. Выделенные подходы определяют значение на графике; невыполненные не учитываются.",
  "Lighter weights or fewer reps may reflect a deliberately easier workout. This chart describes your logs.":
    "Меньший вес или меньше повторений могут отражать намеренно лёгкую тренировку. График показывает ваши записи.",
  "Tap a point to see its completed sets, previous result and original workout. Volume sums weight × reps for completed sets of each exercise per day.":
    "Нажмите на точку, чтобы увидеть выполненные подходы, предыдущий результат и тренировку. Объём — сумма веса × повторений выполненных подходов упражнения за день.",
  Illustrations: "Иллюстрации",
  "Customize images for this profile. Transparent images work best.":
    "Настройте изображения для этого профиля. Лучше использовать прозрачный фон.",
  Placement: "Размещение",
  Layout: "Устройство",
  Desktop: "Компьютер",
  Phone: "Телефон",
  "Upload image": "Загрузить изображение",
  Preview: "Предпросмотр",
  "Image size": "Размер изображения",
  "Left / right": "Влево / вправо",
  "Up / down": "Вверх / вниз",
  "Move right or down with positive values. Dashboard phone placement is saved separately.":
    "Положительные значения сдвигают вправо или вниз. Размещение на телефоне сохраняется отдельно.",
  "Reset illustration": "Сбросить иллюстрацию",
  "Save illustrations": "Сохранить иллюстрации",
  "Illustrations saved.": "Иллюстрации сохранены.",
  "Could not save illustrations.": "Не удалось сохранить иллюстрации.",
  "Could not read this image.": "Не удалось прочитать изображение.",
  "Illustration controls will be available after the account update.":
    "Настройка иллюстраций станет доступна после обновления базы данных.",
  "Expand completed session": "Развернуть выполненную тренировку",
  "Collapse completed session": "Свернуть выполненную тренировку",
  Collapse: "Свернуть",
  "Close navigation": "Закрыть меню",
  "Planner header": "Заголовок планировщика",
  "Analytics header": "Заголовок аналитики",
  "Unread inbox · empty": "Входящие · нет непрочитанных",
  "Today's workout · empty": "Сегодняшняя тренировка · пусто",
  "Show illustration": "Показывать иллюстрацию",
  "Move right or down with positive values. Phone placement is saved separately.":
    "Положительные значения сдвигают вправо или вниз. Положение на телефоне сохраняется отдельно.",
  "New placements need the illustration sections account update (012).":
    "Для новых областей иллюстраций обновите базу данных (012).",
};
